<header>
    <div class="header"><?php echo $this->translate('Add New Employee'); ?></div>
</header>

<p>Company: <b><?php echo $company->name; ?></b></p>

<?php echo $this->form()->openTag($form); ?>

<div class="form">
    <fieldset>
        <div><?php echo $this->formRow($form->get('name')); ?></div>
        <div><?php echo $this->formRow($form->get('lastname')); ?></div>
        <div><?php echo $this->formRow($form->get('email')); ?></div>
        <div><?php echo $this->formRow($form->get('startdate')); ?></div>
        <div><?php echo $this->formSubmit($form->get('submit')); ?></div>
        <input type="hidden" name="cid" value="<?php echo $company->id; ?>"/>
    </fieldset>
</div>

<?php echo $this->form()->closeTag(); ?>
