<header><div class="header">Užduoties aprašymas</div></header>

<p>Užduočiai naudojau Zend 2.2.5, MySQL 5.5.35, Ubuntu 12.04, Netbeans 7.4, Apache httpd 2.2.22, jQuery 1.11.0 bei Yahoo YUI 3.</p>

<p>Daugiausia laiko užtrukau modeliui, nes kurdamas tuo pačiu ir mokinausi Zend 2. Companies modelis naudoja PHP validacijos filtrus ir form builder-į, o Employees naudojau Doctrine annotations.</p>

<p>Kompanijoms sukūriau validatorių neleisti dublikuotis pavadinimui, o darbuotojo datai naudojau DateTime::createFromFormat.</p>

<p>EmployeeStartdateValidator::validateDate yra vienintelė ne mano funkcija visame kode.</p>

<p>Mark up-ui naudojau HTML5 elementus kaip header, article ir kt.</p>

<p>Layout'as turi max 800px ilgį. Tačiau yra responsive: siaurinant, langas prisitaiko prie pločio.</p>

<p>Ištryniau visus ZEND 2 pirminius CSS stilius ir pritaikiau savąjį.</p>

<p>Šiuo metu trūksta tiktai javascript formų validacijos. Taip pat norėčiau darbuotojo darbo pradžios datą formoje pakeisti iš tekstinio lauko į tris &lt;select&gt; elementus.</p>

<p>Duomenų bazėje naudojau InnoDB lentleles, kuriomis kompanijas susiejau su darbuotojais, one-to-many.</p>