<header><div class="header">Užduoties aprašymas</div></header>

<p>Užduočiai naudojau Zend 2.2.5, MySQL 5.5.35, Ubuntu 12.04, Netbeans 7.4, Apache httpd 2.2.22, jQuery 1.11.0 bei Yahoo YUI 3.</p>

<p>Daugiausia laiko užtrukau modeliui, nes kurdamas tuo pačiu ir mokinausi Zend 2. Kompanijų objektas naudoja filtrus ir form builder-į php kodu, o Employees klasei naudojau anotacijas, kas gerokai sumažina kodo kiekį.</p>
<p>Nemažai naudojau service locator-ių bei</p>

<p>Kompanijoms sukūriau validatorių neleisti dublikuotis pavadinimui, o darbuotojo datai naudojau DateTime::createFromFormat.</p>
<p>Validavimas yra visiškai analogiškas serveryje bei client-ende. Prie to dirbau nemažai. Sukūriau myValidator javascript objektą bei validateJSON action’us kontroleriuose.</p>

<p>EmployeeStartdateValidator::validateDate yra vienintelė ne mano funkcija visame kode.</p>

<p>Mark up-ui naudojau HTML5 elementus kaip header, article ir kt.</p>

<p>Layout'as turi max 800px ilgį. Tačiau yra responsive: siaurinant, langas prisitaiko prie pločio.</p>

<p>Ištryniau visus ZEND 2 pirminius CSS stilius ir pritaikiau savąjį. Baziniams stiliams bei grid’ams naudojau YUI-3.</p>

<p>Duomenų bazėje naudojau InnoDB lentleles, kuriomis kompanijas susiejau su darbuotojais.</p>
<p>Manau, visa aplikacija sumodeliuota neblogai. Ištestuoti visko gerai neturėjau laiko. Idealu būtų kodą pritaikyti unit testams.</p>
<p>Pati išvaizda nėra įspūdinga, bet pasiekiau visą reikiamą funkcionalumą. Manau, svarbiausia - kaip tai padariau.</p>
<p>Visoje aplikacijoje naudojau anglų kalbą, bet tekstus rašiau su zend translator, tad galima išversti.</p>
<p align="right">Arnoldas</p>